### ISSUE TITLE
Feature Request: Idle Pause

### ISSUE THREAD

**Issue by ghost** [Killface1980/RW_ColonistBarKF#28]
I thought about making this a mod request on the forum, but given your mod is already constantly monitoring the pawn states, I figured I'd ask you first.

Would you be willing to implement a feature that automatically pauses the game the moment a pawn becomes idle, as in has nothing to do?

**Comment by ghost** [comment]
Hey, just wondering if you liked this idea or not. If not I'll pitch it elsewhere.

**Comment by tommargar** [comment]
sorry for not answering, was busy IRL + fixing some stuff. I guess this is better suited as a mini-mod on its own. my main focus at the moment is fixing existing features und cleaning up. you can pitch your idea in the forums, but I can't tell you when I'm able to make something like this, sorry.

By the way, I got bug reports about memory leaks and crashes with the colonist bar. Have you noticed anything like that on your machine?

**Comment by ghost** [comment]
No, the only memory leak I've experienced so far was with PeteTimesSix's QOL Tweaks mod, which is presumably fixed now.

**Comment by Miner239** [comment]
I do have a crash with the stacktrace leading to this mod. Here's the post-crashy stuff:
[2017-07-08_144208.zip](https://github.com/Killface1980/RW_ColonistBarKF/files/1132891/2017-07-08_144208.zip)

While I'm here, can you add an option to disable individual tabs? I don't use the Thoughts tab anyway.

**Comment by tommargar** [comment]
@Miner239 just uploaded a fix at https://github.com/Killface1980/RW_ColonistBarKF/archive/A17_rewrite.zip 
please test and see if the bug still appears. for the icons, right click on any colonist icon and go to the settings. nearly everything is customizable.

**Comment by Miner239** [comment]
Oh, right. I might have confused this and Moody.

**Comment by Miner239** [comment]
I am still getting crashes. I noticed that the game crash log is exactly 62 minutes after the output log is first generated (I now have four crashlog, the first one also has 62 minutes delay, and the latter 2 crashes' logs generate at the same time as the crash). I suspect that something is ticking, then overflows causing something to crash...
[2017-07-09_184952.zip](https://github.com/Killface1980/RW_ColonistBarKF/files/1133751/2017-07-09_184952.zip)

**Comment by tommargar** [comment]
Uploaded a possible fix. In this mod, there's nothing cumulative ticking, each pawn check is done after a random time.

**Comment by Miner239** [comment]
I got a different crash this time using the rewrite version. [output_log.txt](https://github.com/Killface1980/RW_ColonistBarKF/files/1134572/output_log.txt)
Here's a [modlist.txt](https://github.com/Killface1980/RW_ColonistBarKF/files/1134584/modlist.txt) if it helps.

**Comment by tommargar** [comment]
Now I guess that CBKF was just crashing, but not causing this. Seems to be a thought with its missing or malformed LabelCap, which lead CBKF and Vanilla to crash. From a look at your mod list I suspect Psychology, but can't track this down any further.
